blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.StartingPageView.as_view(), name="starting-page"),
    path("posts", views.AllPostsView.as_view(), name="posts-page"),
    path("posts/<slug:slug>", views.SinglePostView.as_view(),
         name="post-detail-page"),  # /posts/my-first-post
    path("read-later", views.ReadLaterView.as_view(), name="read-later")
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("", include("blog.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    
    # ex: /polls/
    path("", views.IndexView.as_view(), name="index"),
    
    # ex: polls/5/
    path("<int:pk>", views.DetailView.as_view(), name = "detail" ),
    
    # ex: polls/5/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
     
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"), 
    
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?"
    )
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

polls/views.py
from typing import Any
from django.db.models import F
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

"""Each generic view needs to know what model it will be acting upon. 
    This is provided using either the model attribute (in this example, 
    model = Question for DetailView and ResultsView) or by defining the 
    get_queryset() method (as shown in IndexView)."""

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"
    
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
        :5
    ]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"
    
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save() 
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        #  HttpResponseRedirect takes a single argument: the URL to which the user will be redirected 
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))    




# OLD: 
    
#def index(request):
 #   latest_question_list = Question.objects.order_by("-pub_date")[:5]
  #  context = {"latest_question_list": latest_question_list}
   # return render(request, "polls/index.html", context)

""" def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id) 
    return render(request, "polls/detail.html", {"question": question}) """
                  
""" def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question}) """

polls/templates/polls/detail.html
<h1> {{ question.question_text }}</h1>
<ul>
    <!-- The template system uses dot-lookup syntax to 
    access variable attributes. In the example of 
    {{ question.question_text }},-->
    {% for choice in question.choice_set.all %}
        <li> {{ choice.choice_text }} </li>
    {% endfor %}
</ul>

<!-- template displays a radio button for each question choice.-->
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1/</legend>
    {% if error_message %}<p><strong>{{ error_message}}</strong></p>
{% endif %}
    {% for choice in question.choice_set.all %}
        <!-- The value of each radio button is the associated question choice’s ID. -->
        <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{choice.choice_text }}</label>
        <br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}"

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available/</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>